name: arkit_plugin
description: Flutter Plugin for ARKit - Apple's augmented reality (AR) development platform for iOS mobile devices.
version: 0.6.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  vector_math: ^2.0.8
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.7.1
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArkitPlugin
